# Generated by Django 5.1.5 on 2025-01-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('postDate', models.DateTimeField()),
                ('likes', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.BigIntegerField(default=0),
        ),
    ]
