# Generated by Django 5.1.5 on 2025-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('postID', models.CharField(max_length=150)),
                ('isLiked', models.BooleanField(default=False)),
            ],
        ),
    ]
