# Generated by Django 5.1.5 on 2025-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_liketracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='currentlyFollow',
            field=models.BooleanField(default=False),
        ),
    ]
