# Generated by Django 5.1.5 on 2025-01-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow_currentlyfollow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='currentlyFollow',
        ),
    ]
